name: data-analysis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - aom=3.7.1=h463b476_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - blosc=1.21.5=hc338f07_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brunsli=0.1=h9f76cd9_0
  - bzip2=1.0.8=h93a5062_5
  - c-ares=1.28.1=h93a5062_0
  - c-blosc2=2.12.0=ha57e6be_0
  - ca-certificates=2024.2.2=hf0a4a13_0
  - cairo=1.18.0=hd1e100b_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charls=2.4.2=h13dd4ca_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorlog=6.8.2=py311h267d04e_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.1=py311hcc98501_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hb547adb_0
  - debugpy=1.8.1=py311h92babd0_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - easydev=0.12.0=pyh6c4a22f_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=hebf3989_0
  - ffmpeg=6.1.0=gpl_hb51155c_103
  - fitter=1.4.1=pyh5e36f6f_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py311h05b510d_0
  - freetype=2.12.1=hadb7bae_2
  - fribidi=1.0.10=h27ca646_0
  - gettext=0.22.5=h8fbad5d_2
  - gettext-tools=0.22.5=h8fbad5d_2
  - giflib=5.2.2=h93a5062_0
  - gmp=6.3.0=hebf3989_1
  - gnutls=3.7.9=hd26332c_0
  - graphite2=1.3.13=hebf3989_1003
  - harfbuzz=7.3.0=hf1a6348_1
  - hdf5=1.14.3=nompi_h751145d_101
  - icu=73.2=hc8870d7_0
  - imagecodecs=2023.9.4=py311ha7c5239_0
  - imageio=2.34.0=pyh4b66e23_0
  - imglyb=2.1.0=pyha21a80b_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyh3cd1d5f_0
  - jasper=4.0.0=hff9eb24_1
  - jedi=0.19.1=pyhd8ed1ab_0
  - jgo=1.0.5=pyhd8ed1ab_0
  - joblib=1.4.0=pyhd8ed1ab_0
  - jpype1=1.5.0=py311hcc98501_1
  - jsonschema=4.21.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h267d04e_0
  - jxrlib=1.1=h93a5062_3
  - kiwisolver=1.4.5=py311he4fd1f5_1
  - krb5=1.21.2=h92f50d5_0
  - labeling=0.1.12=pyhd8ed1ab_1
  - lame=3.100=h1a8c8d9_1003
  - latexify-py=0.4.3.post1=pyhd8ed1ab_0
  - lazy_loader=0.4=pyhd8ed1ab_0
  - lcms2=2.15=hd835a16_1
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20230802.1=cxx17_h13dd4ca_0
  - libaec=1.1.3=hebf3989_0
  - libasprintf=0.22.5=h8fbad5d_2
  - libasprintf-devel=0.22.5=h8fbad5d_2
  - libass=0.17.1=h4da34ad_0
  - libavif16=1.0.3=h4cb461b_0
  - libblas=3.9.0=22_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=22_osxarm64_openblas
  - libcurl=8.7.1=h2d989ff_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.18=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h93a5062_2
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.2=h3422bc3_5
  - libgettextpo=0.22.5=h8fbad5d_2
  - libgettextpo-devel=0.22.5=h8fbad5d_2
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libglib=2.80.2=h535f939_0
  - libhwloc=2.10.0=default_h52d8fe8_1000
  - libhwy=1.1.0=h2ffa867_0
  - libiconv=1.17=h0d3ecfb_2
  - libidn2=2.3.7=h93a5062_0
  - libintl=0.22.5=h8fbad5d_2
  - libintl-devel=0.22.5=h8fbad5d_2
  - libjpeg-turbo=2.1.5.1=hb547adb_1
  - libjxl=0.10.1=h07599a0_1
  - liblapack=3.9.0=22_osxarm64_openblas
  - liblapacke=3.9.0=22_osxarm64_openblas
  - libnghttp2=1.58.0=ha4dd798_1
  - libopenblas=0.3.27=openmp_h6c19121_0
  - libopencv=4.8.0=py311he247fa4_2
  - libopenvino=2023.0.2=h13dd4ca_0
  - libopenvino-arm-cpu-plugin=2023.0.2=h13dd4ca_0
  - libopenvino-auto-batch-plugin=2023.0.2=h13dd4ca_0
  - libopenvino-auto-plugin=2023.0.2=h13dd4ca_0
  - libopenvino-hetero-plugin=2023.0.2=h13dd4ca_0
  - libopenvino-ir-frontend=2023.0.2=h13dd4ca_0
  - libopenvino-onnx-frontend=2023.0.2=h13dd4ca_0
  - libopenvino-paddle-frontend=2023.0.2=h13dd4ca_0
  - libopenvino-pytorch-frontend=2023.0.2=h13dd4ca_0
  - libopenvino-tensorflow-frontend=2023.0.2=h13dd4ca_0
  - libopenvino-tensorflow-lite-frontend=2023.0.2=h13dd4ca_0
  - libopus=1.3.1=h27ca646_1
  - libpng=1.6.43=h091b4b1_0
  - libprotobuf=4.23.4=hf590ac1_6
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.45.2=h091b4b1_0
  - libssh2=1.11.0=h7a5bd25_0
  - libtasn1=4.19.0=h1a8c8d9_0
  - libtiff=4.5.1=h23a1a89_1
  - libunistring=0.9.10=h3422bc3_0
  - libvpx=1.13.1=hb765f3a_0
  - libwebp-base=1.4.0=h93a5062_0
  - libxcb=1.15=hf346824_0
  - libxml2=2.12.7=ha661575_0
  - libzlib=1.2.13=h53f4e23_5
  - libzopfli=1.0.3=h9f76cd9_0
  - llvm-openmp=18.1.3=hcd81f8e_0
  - lz4-c=1.9.4=hb7217d7_0
  - matplotlib=3.8.4=py311ha1ab1f8_0
  - matplotlib-base=3.8.4=py311hb58f1d1_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - maven=3.9.6=hce30654_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.4.20240210=h078ce10_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.9.1=h40ed0f5_0
  - networkx=3.3=pyhd8ed1ab_1
  - numpy=1.26.4=py311h7125741_0
  - opencv=4.8.0=py311ha1ab1f8_2
  - openh264=2.4.0=h965bd2d_0
  - openjdk=11.0.22=h3fcba2d_0
  - openjpeg=2.5.0=hbc2ba62_2
  - openpyxl=3.1.2=py311heffc1b2_0
  - openssl=3.3.0=h0d3ecfb_0
  - p11-kit=0.24.1=h29577a5_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=1.5.3=py311h4eec4a9_1
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.43=h26f9a81_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.5.0=py311h095fde6_1
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.4=hebf3989_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - plotly=5.22.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py311h05b510d_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pugixml=1.13=h13dd4ca_1
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-opencv=4.8.0=py311hf3b2ce4_2
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyimagej=1.4.1=py311h267d04e_1
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - python=3.11.0=h3ba56d0_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pywavelets=1.4.1=py311hb49d859_1
  - pyzmq=26.0.0=py311he9c0408_0
  - rav1e=0.6.6=h69fbcac_2
  - readline=8.2=h92ec313_1
  - referencing=0.34.0=pyhd8ed1ab_0
  - rpds-py=0.18.0=py311ha958965_0
  - scikit-learn=1.4.2=py311h696fe38_0
  - scipy=1.13.0=py311h4f9446f_0
  - scyjava=1.9.1=pyhd8ed1ab_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hd04f947_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statannotations=0.6.0=pyhd8ed1ab_0
  - statsmodels=0.14.1=py311h9ea6feb_0
  - svt-av1=1.7.0=hb765f3a_0
  - tbb=2021.12.0=h2ffa867_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - threadpoolctl=3.4.0=pyhc1e730c_0
  - tifffile=2024.2.12=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tornado=6.4=py311h05b510d_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xarray=2024.3.0=pyhd8ed1ab_0
  - xlsxwriter=3.1.9=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - zeromq=4.3.5=hebf3989_1
  - zfp=1.0.1=ha8f4885_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h53f4e23_5
  - zlib-ng=2.0.7=h1a8c8d9_0
  - zstd=1.5.5=h4f39d0f_0
  - pip:
      - aiofiles==22.1.0
      - aiohttp==3.9.4
      - aiosignal==1.3.1
      - aiosqlite==0.20.0
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cffi==1.16.0
      - cftime==1.6.3
      - charset-normalizer==3.3.2
      - cloudpickle==3.0.0
      - colorcet==3.1.0
      - dask==2024.4.1
      - dask-expr==1.0.11
      - dask-image==2023.8.1
      - defusedxml==0.7.1
      - elfinder-client==2.1.62a3
      - fastapi==0.110.1
      - fasteners==0.19
      - filelock==3.13.4
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - h11==0.14.0
      - httptools==0.6.1
      - idna==3.7
      - ij==0.0.4
      - imagej==0.3.1
      - imjoy-elfinder==0.1.63
      - imjoy-jupyter-extension==0.3.0
      - imjoy-jupyterlab-extension==0.2.6
      - imjoy-rpc==0.5.48.post2
      - imjoy-utils==0.1.2
      - ipydatawidgets==4.3.2
      - ipympl==0.9.4
      - ipython==8.21.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.8.1
      - isoduration==20.11.0
      - itk==5.3.0
      - itk-core==5.3.0
      - itk-filtering==5.3.0
      - itk-io==5.3.0
      - itk-meshtopolydata==0.10.0
      - itk-numerics==5.3.0
      - itk-registration==5.3.0
      - itk-segmentation==5.3.0
      - itkwasm==1.0b171
      - itkwasm-downsample==1.1.0
      - itkwasm-downsample-wasi==1.1.0
      - itkwidgets==1.0a49
      - jinja2==3.1.3
      - json5==0.9.25
      - jsonpointer==2.4
      - jupyter-events==0.10.0
      - jupyter-server==2.14.0
      - jupyter-server-fileid==0.9.1
      - jupyter-server-proxy==4.1.2
      - jupyter-server-terminals==0.5.3
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.5
      - jupyterlab==3.6.7
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.26.0
      - jupyterlab-widgets==1.1.7
      - locket==1.0.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mistune==3.0.2
      - monai==1.3.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - nbclassic==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - netcdf4==1.6.5
      - ngff-zarr==0.8.1
      - nibabel==5.2.1
      - notebook==6.4.13
      - notebook-shim==0.2.4
      - numcodecs==0.12.1
      - overrides==7.7.0
      - pandas-flavor==0.6.0
      - pandocfilters==1.5.1
      - partd==1.4.1
      - pathvalidate==3.2.0
      - pims==0.6.1
      - pingouin==0.5.4
      - pooch==1.8.1
      - prometheus-client==0.20.0
      - pyarrow==15.0.2
      - pycparser==2.22
      - pydantic==1.10.15
      - pyjnius==1.6.1
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.9
      - pyvista==0.43.5
      - pyyaml==6.0.1
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - scikit-image==0.23.1
      - scooby==0.9.2
      - send2trash==1.8.3
      - shortuuid==1.0.13
      - simpervisor==1.0.0
      - slicerator==1.1.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - starlette==0.37.2
      - sympy==1.12
      - tabulate==0.9.0
      - terminado==0.18.1
      - tinycss2==1.2.1
      - toolz==0.12.1
      - torch==2.2.2
      - tqdm==4.66.2
      - traitlets==5.6.0
      - traittypes==0.2.1
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - urllib3==2.2.1
      - ut==0.2.0
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - vtk==9.3.0
      - wasmtime==19.0.0
      - watchfiles==0.21.0
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - websockets==12.0
      - widgetsnbextension==3.6.6
      - y-py==0.6.2
      - yarl==1.9.4
      - ypy-websocket==0.8.4
      - zarr==2.17.2
      - zstandard==0.22.0
